version: '2'

services:
  react:
    build: client
    ports:
      - "3001:3001"

  express:
    build: server
    ports:
      - "3000:3000"

  database:
    image: mongo
    ports:
      - "27017:27017"