version: '2'

services:
  react:
    build: client
    dockerfile: Dockerfile-production
    ports:
      - "3001:3001"

  express:
    build: server
    dockerfile: Dockerfile-production
    ports:
      - "3000:3000"
    links:
      - database

  database:
    image: mongo
    ports:
      - "27017:27017"