version: '2'

services:
  react:
    build: client
    ports:
      - "3001:3001"
    volumes:
      - ./client:/usr/src/app

  express:
    build: server
    ports:
      - "3000:3000"
    links:
      - database
    volumes:
      - ./server:/usr/src/app

  database:
    image: mongo
    ports:
      - "27017:27017"